export const GET_ERROR = "GET_ERROR";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
